-- Tạo role ADMIN, RECRUITER, CANDIDATE nếu chưa có
INSERT INTO roles (name)
SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ADMIN');

INSERT INTO roles (name)
SELECT 'RECRUITER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='RECRUITER');

INSERT INTO roles (name)
SELECT 'CANDIDATE' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='CANDIDATE');
